version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - echo Installing Hugo
      - cd ~
      - wget https://github.com/gohugoio/hugo/releases/download/v0.69.1/hugo_extended_0.69.1_Linux-64bit.deb
      - dpkg -i hugo*.deb
      - hugo version
  build:
    commands:
      - echo BUILD phase commands
      - cd $CODEBUILD_SRC_DIR/content/posts
      - ls -l
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - hugo -v
      - aws s3 ls
      - aws s3 sync --delete public s3://shyamramineni.com
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
